/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ainokila
 */
public class VentanaTamanioDialog extends javax.swing.JDialog {

    /**
     * Creates new form TamanioVentanaDialog
     * @param parent Padre de la ventana
     * @param modal 
     */
    private int altura;
    private int ancho;
    
    public VentanaTamanioDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAltura = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAncho = new javax.swing.JTextPane();
        aceptar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 210));

        jLabel2.setText("Altura");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 40, -1));

        jLabel3.setText("Ancho");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 40, -1));

        jScrollPane1.setViewportView(textAltura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, -1));

        jScrollPane3.setViewportView(textAncho);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 70, -1));

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });
        getContentPane().add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        
        try{
            this.altura = new Integer(this.textAltura.getText());
            this.ancho  = new Integer(this.textAncho.getText());
            
        }catch(Exception e){
            System.err.println("Error al convertir a numero");
        }
        this.dispose();


    }//GEN-LAST:event_aceptarMouseClicked

    public int getAltura(){
        return altura;
    }
    
    public int getAncho(){
        return ancho;      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane textAltura;
    private javax.swing.JTextPane textAncho;
    // End of variables declaration//GEN-END:variables
}
