/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import sm.cvr.iu.*;

/**
 *
 * @author Ainokila
 */
public class Principal extends javax.swing.JFrame {

    EnumHerramienta herramientaActiva;
    EnumColor colorActivo;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        inicializa();
    }

    private void inicializa(){
        
        //Color
        herramientaActiva = EnumHerramienta.LAPIZ;
        colorActivo = EnumColor.NEGRO;
        this.grosor.setValue(1);
        
        this.btn_punto.setSelected(true);
        
        
        this.selector_color.removeAllItems();

        this.selector_color.addItem("Negro");
        this.selector_color.addItem("Rojo");
        this.selector_color.addItem("Azul");
        this.selector_color.addItem("Blanco");
        this.selector_color.addItem("Amarillo");
        this.selector_color.addItem("Verde");
        
        this.selector_color.addActionListener(new ActionListener () {
            @Override
            public void actionPerformed(ActionEvent ae) {
                //Cambiar color
                
                switch ((String)selector_color.getSelectedItem()){
                    case "Negro":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.NEGRO);
                         colorActivo = EnumColor.NEGRO;
                        break;
                    case "Rojo":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.ROJO);
                         colorActivo = EnumColor.ROJO;
                        break;
                    case "Azul":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.AZUL);
                         colorActivo = EnumColor.AZUL;
                        break;
                    case "Blanco":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.BLANCO);
                         colorActivo = EnumColor.BLANCO;
                        break;
                    case "Amarillo":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.AMARILLO); 
                         colorActivo = EnumColor.AMARILLO;
                        break;
                    case "Verde":
                         for(JInternalFrame i: escritorio.getAllFrames())
                             if(i.isSelected())
                            ((VentanaInterna)i).getLienzo().setColor(EnumColor.VERDE);
                         colorActivo = EnumColor.VERDE;
                        break;
             }
            }
        });
        
        //GROSOR
            grosor.addChangeListener(new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent e) {
                int valor = 1;

           try{
               valor = (int)grosor.getValue();
           }catch(Exception eX){
               System.err.println("Error excepcion");
           }
            System.out.println("valor");

           if(valor<=0){
               valor = 1;
           }
           
           if(valor>=21){
               valor = 20;
           }

           grosor.setValue(valor);
           for(JInternalFrame i: escritorio.getAllFrames()){
               if(i.isSelected())
                    ((VentanaInterna)i).getLienzo().setGrosor(valor);                
            }
        }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        herramientas = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btn_nuevo = new javax.swing.JButton();
        btn_abrir = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_punto = new javax.swing.JToggleButton();
        btn_linea = new javax.swing.JToggleButton();
        btn_rectangulo = new javax.swing.JToggleButton();
        btn_elipse = new javax.swing.JToggleButton();
        btn_edicion = new javax.swing.JToggleButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        selector_color = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        grosor = new javax.swing.JSpinner();
        btn_relleno = new javax.swing.JToggleButton();
        btn_transparencia = new javax.swing.JToggleButton();
        btn_alisar = new javax.swing.JToggleButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        barraEstado = new javax.swing.JCheckBoxMenuItem();
        barraFormas = new javax.swing.JCheckBoxMenuItem();
        barraAtributos = new javax.swing.JCheckBoxMenuItem();
        imagen = new javax.swing.JMenu();
        tamNuevaImagen = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        estado.setText("Estado");
        jPanel1.add(estado);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jToolBar2.setRollover(true);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/nuevo.png"))); // NOI18N
        btn_nuevo.setFocusable(false);
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nuevoMouseClicked(evt);
            }
        });
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_nuevo);

        btn_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/abrir.png"))); // NOI18N
        btn_abrir.setFocusable(false);
        btn_abrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_abrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_abrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_abrirMouseClicked(evt);
            }
        });
        btn_abrir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_abrirKeyPressed(evt);
            }
        });
        jToolBar2.add(btn_abrir);

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/guardar.png"))); // NOI18N
        btn_guardar.setFocusable(false);
        btn_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        jToolBar2.add(btn_guardar);
        jToolBar2.add(jSeparator1);

        herramientas.add(btn_punto);
        btn_punto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/punto.png"))); // NOI18N
        btn_punto.setFocusable(false);
        btn_punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_punto);

        herramientas.add(btn_linea);
        btn_linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/linea.png"))); // NOI18N
        btn_linea.setFocusable(false);
        btn_linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lineaActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_linea);

        herramientas.add(btn_rectangulo);
        btn_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/rectangulo.png"))); // NOI18N
        btn_rectangulo.setFocusable(false);
        btn_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_rectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rectanguloActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_rectangulo);

        herramientas.add(btn_elipse);
        btn_elipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/elipse.png"))); // NOI18N
        btn_elipse.setFocusable(false);
        btn_elipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_elipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elipseActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_elipse);

        herramientas.add(btn_edicion);
        btn_edicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/seleccion.png"))); // NOI18N
        btn_edicion.setFocusable(false);
        btn_edicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_edicion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_edicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_edicionMouseClicked(evt);
            }
        });
        btn_edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edicionActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_edicion);
        jToolBar2.add(jSeparator2);

        selector_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selector_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selector_colorActionPerformed(evt);
            }
        });
        jToolBar2.add(selector_color);
        jToolBar2.add(jSeparator3);

        grosor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grosorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grosorMouseEntered(evt);
            }
        });
        jToolBar2.add(grosor);

        btn_relleno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/rellenar.png"))); // NOI18N
        btn_relleno.setFocusable(false);
        btn_relleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_relleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_relleno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rellenoMouseClicked(evt);
            }
        });
        jToolBar2.add(btn_relleno);

        btn_transparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/transparencia.png"))); // NOI18N
        btn_transparencia.setFocusable(false);
        btn_transparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_transparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_transparencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_transparenciaMouseClicked(evt);
            }
        });
        btn_transparencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transparenciaActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_transparencia);

        btn_alisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/alisar.png"))); // NOI18N
        btn_alisar.setFocusable(false);
        btn_alisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_alisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_alisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_alisarMouseClicked(evt);
            }
        });
        jToolBar2.add(btn_alisar);

        jPanel4.add(jToolBar2, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        escritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escritorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jPanel2.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu3.setText("Archivo");

        nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/nuevo.png"))); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jMenu3.add(nuevo);

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/abrir.png"))); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu3.add(abrir);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica7/iconos/guardar.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu3.add(guardar);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edicion");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        barraEstado.setSelected(true);
        barraEstado.setText("Barra Estado");
        barraEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraEstadoMouseClicked(evt);
            }
        });
        barraEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraEstadoActionPerformed(evt);
            }
        });
        jMenu4.add(barraEstado);

        barraFormas.setSelected(true);
        barraFormas.setText("Barra de Formas");
        barraFormas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraFormasMouseClicked(evt);
            }
        });
        barraFormas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraFormasActionPerformed(evt);
            }
        });
        jMenu4.add(barraFormas);

        barraAtributos.setSelected(true);
        barraAtributos.setText("Barra de Atributos");
        barraAtributos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barraAtributosMouseClicked(evt);
            }
        });
        barraAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraAtributosActionPerformed(evt);
            }
        });
        jMenu4.add(barraAtributos);

        jMenuBar2.add(jMenu4);

        imagen.setText("Imagen");

        tamNuevaImagen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        tamNuevaImagen.setText("Tamaño nueva imagen");
        imagen.add(tamNuevaImagen);

        jMenuBar2.add(imagen);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selector_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selector_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selector_colorActionPerformed

    private void btn_transparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transparenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_transparenciaActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setHerramienta(EnumHerramienta.LAPIZ);
                ((VentanaInterna)i).getLienzo().setEditar(false);
            }

        }
        this.estado.setText(EnumHerramienta.LAPIZ.toString());
        this.herramientaActiva = EnumHerramienta.LAPIZ;
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lineaActionPerformed
       for(JInternalFrame i: this.escritorio.getAllFrames()){
           if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setHerramienta(EnumHerramienta.LINEA);
                ((VentanaInterna)i).getLienzo().setEditar(false);
           }
        }
       this.estado.setText(EnumHerramienta.LINEA.toString());
       this.herramientaActiva = EnumHerramienta.LINEA;
    }//GEN-LAST:event_btn_lineaActionPerformed

    private void btn_rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rectanguloActionPerformed
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setHerramienta(EnumHerramienta.RECTANGULO);
                ((VentanaInterna)i).getLienzo().setEditar(false);
            }
        }
        this.estado.setText(EnumHerramienta.RECTANGULO.toString());
        this.herramientaActiva = EnumHerramienta.RECTANGULO;
    }//GEN-LAST:event_btn_rectanguloActionPerformed

    private void btn_elipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elipseActionPerformed
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setHerramienta(EnumHerramienta.CIRCULO);
                ((VentanaInterna)i).getLienzo().setEditar(false);
            }
        }
        this.estado.setText(EnumHerramienta.CIRCULO.toString());
        this.herramientaActiva = EnumHerramienta.CIRCULO;
    }//GEN-LAST:event_btn_elipseActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
          aniadeInternalFrame();
    }//GEN-LAST:event_nuevoActionPerformed

    private void aniadeInternalFrame(){
        VentanaInterna v = new VentanaInterna(this);

        v.getLienzo().setLienzo(EnumHerramienta.LAPIZ, EnumColor.NEGRO,1, false,false,false,false);
        v.setVisible(true);
        

        escritorio.setLayer(v, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        
        
    }
    //No Actualiza herramientas al seleccionar el nuevo lienzo
    private void escritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseClicked
    }//GEN-LAST:event_escritorioMouseClicked

    private void grosorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grosorMouseClicked
        
    }//GEN-LAST:event_grosorMouseClicked

    private void grosorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grosorMouseEntered
       
    }//GEN-LAST:event_grosorMouseEntered

    private void btn_rellenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rellenoMouseClicked

        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected())
                ((VentanaInterna)i).getLienzo().setRellenar(btn_relleno.isSelected());
        }
 

    }//GEN-LAST:event_btn_rellenoMouseClicked

    private void btn_transparenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_transparenciaMouseClicked
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setTransparencia(btn_transparencia.isSelected());
                ((VentanaInterna)i).getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_btn_transparenciaMouseClicked

    private void btn_alisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_alisarMouseClicked
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setAlisado(btn_alisar.isSelected());
                ((VentanaInterna)i).getLienzo().repaint();
            }
        }
    }//GEN-LAST:event_btn_alisarMouseClicked

    private void btn_edicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_edicionMouseClicked
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                ((VentanaInterna)i).getLienzo().setHerramienta(EnumHerramienta.NINGUNO);
                ((VentanaInterna)i).getLienzo().setEditar(btn_edicion.isSelected());
                ((VentanaInterna)i).getLienzo().repaint();
            }
        }
        this.estado.setText("Edicionf");
    }//GEN-LAST:event_btn_edicionMouseClicked

    private void btn_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nuevoMouseClicked
        aniadeInternalFrame();
    }//GEN-LAST:event_btn_nuevoMouseClicked

    private void btn_abrirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_abrirKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_abrirKeyPressed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        guardar();
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_abrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_abrirMouseClicked
        abrir();
    }//GEN-LAST:event_btn_abrirMouseClicked

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        abrir();
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        guardar();
    }//GEN-LAST:event_guardarActionPerformed

    private void btn_edicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_edicionActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void barraAtributosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraAtributosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_barraAtributosMouseClicked

    private void barraFormasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraFormasMouseClicked

    }//GEN-LAST:event_barraFormasMouseClicked

    private void barraEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraEstadoMouseClicked

    }//GEN-LAST:event_barraEstadoMouseClicked

    private void barraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraFormasActionPerformed
        boolean state = barraFormas.isSelected();
        this.btn_punto.setVisible(state);
        this.btn_linea.setVisible(state);
        this.btn_rectangulo.setVisible(state);
        this.btn_elipse.setVisible(state);
        this.btn_edicion.setVisible(state);
    }//GEN-LAST:event_barraFormasActionPerformed

    private void barraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraEstadoActionPerformed
        this.estado.setVisible(barraEstado.isSelected());
        this.repaint();
    }//GEN-LAST:event_barraEstadoActionPerformed

    private void barraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraAtributosActionPerformed
        boolean state = barraAtributos.isSelected();
        this.btn_alisar.setVisible(state);
        this.btn_relleno.setVisible(state);
        this.btn_transparencia.setVisible(state);
        this.grosor.setVisible(state);
        this.selector_color.setVisible(state);
    }//GEN-LAST:event_barraAtributosActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void guardar(){
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {

        }
    }

    private void abrir(){
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {

        }
    }
    
   public void setEstado(String sta){
       this.estado.setText(sta);
   }
    
   public void setLapiz(boolean state){
       this.btn_punto.setSelected(state);
   }
   
   public void setLine(boolean state){
       this.btn_linea.setSelected(state);
   }
   
   public void setRectangulo(boolean state){
       this.btn_rectangulo.setSelected(state);
   }
   
   public void setElipse(boolean state){
       this.btn_elipse.setSelected(state);
   }
   
   public void setEdicion(boolean state){
       this.btn_edicion.setSelected(state);
   }
   
   public void setColor(String color){
       //this.selector_color.setSelectedIndex();
       String c = "Negro";
       int pos = 0;
       
        for(JInternalFrame i: this.escritorio.getAllFrames()){
            if(i.isSelected()){
                c = ((VentanaInterna)i).getLienzo().getColor().toString();
            }
        }
        
        switch(c){
            case "Negro":
                pos = 0;      
                break;
            case "Rojo":
                pos = 1;
                break;
            case "Azul":
                pos = 2;
                break;
            case "Blanco":
                pos = 3;
                break;
            case "Amarillo":
                pos = 4;
                break;
            case "Verde":
                pos = 5;
                break;
        }
        this.selector_color.setSelectedIndex(pos);   
   }
   
   public void setGrosor(int gro){
       this.grosor.setValue(gro);
   }
   
   public void setRelleno(boolean state){
       this.btn_relleno.setSelected(state);
   }
   
   public void setTransparencia(boolean state){
       this.btn_transparencia.setSelected(state);
   }
   
      public void setAlisar(boolean state){
       this.btn_alisar.setSelected(state);
   }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JCheckBoxMenuItem barraAtributos;
    private javax.swing.JCheckBoxMenuItem barraEstado;
    private javax.swing.JCheckBoxMenuItem barraFormas;
    private javax.swing.JButton btn_abrir;
    private javax.swing.JToggleButton btn_alisar;
    private javax.swing.JToggleButton btn_edicion;
    private javax.swing.JToggleButton btn_elipse;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JToggleButton btn_linea;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JToggleButton btn_punto;
    private javax.swing.JToggleButton btn_rectangulo;
    private javax.swing.JToggleButton btn_relleno;
    private javax.swing.JToggleButton btn_transparencia;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel estado;
    private javax.swing.JSpinner grosor;
    private javax.swing.JMenuItem guardar;
    private javax.swing.ButtonGroup herramientas;
    private javax.swing.JMenu imagen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JComboBox<String> selector_color;
    private javax.swing.JMenuItem tamNuevaImagen;
    // End of variables declaration//GEN-END:variables

 

        



}
