/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;
import java.awt.Graphics;
import sm.cvr.iu.Lienzo2d;

/**
 *
 * @author Ainokila
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private Lienzo2d lienzo2d1;
    private static int numeroVentana = 0;
    
    private Principal parent;
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInterna(Principal padre) {
        super("Lienzo " + (++numeroVentana),
          true, //resizable
          true, //closable
          true, //maximizable
          true);//iconifiable
        this.parent=padre;
        initComponents();
        inicializa();

    }
    
    public Lienzo2d getLienzo(){
      return lienzo2d1;
    }
    
    private void inicializa(){
        
        lienzo2d1 = new Lienzo2d(this);

        javax.swing.GroupLayout lienzo2d1Layout = new javax.swing.GroupLayout(lienzo2d1);
        lienzo2d1.setLayout(lienzo2d1Layout);
        lienzo2d1Layout.setHorizontalGroup(
            lienzo2d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        lienzo2d1Layout.setVerticalGroup(
            lienzo2d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lienzo2d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo2d1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Cuando se activa la ventana cargamos la info
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
        System.out.println(lienzo2d1.getHerramienta().toString());
        switch(lienzo2d1.getHerramienta()){
            case LAPIZ: 
                parent.setLapiz(true); 
                break;
            case LINEA: 
                parent.setLine(true);
                break;
            case RECTANGULO: 
                parent.setRectangulo(true);
                break;
            case CIRCULO: 
                parent.setElipse(true);
                break;
            case NINGUNO: break;
        }
        
        parent.setEstado(lienzo2d1.getHerramienta().toString());
        
        parent.setColor(lienzo2d1.getColor().toString());
        parent.setGrosor(lienzo2d1.getGrosor());
        parent.setRelleno(lienzo2d1.getRellenar());
        parent.setAlisar(lienzo2d1.getAlisado());
        parent.setTransparencia(lienzo2d1.getTransparencia());
        
    }

    @Override
    public void paint(Graphics g){
       super.paint(g);
       //this.padre.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
