/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import java.io.File;
import practicaFinal.Principal;
import sm.sound.SMSoundRecorder;

/**
 *
 * @author Ainokila
 */
public class VentanaInternaGrabador extends javax.swing.JInternalFrame {
    
    private Principal parent;
    private SMSoundRecorder recorder;
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInternaGrabador(Principal padre,File f) {
        super(f.getName(),
          true, //resizable
          true, //closable
          true, //maximizable
          true);//iconifiable
                
        //this.setSize(0, 0);
        this.parent=padre;
        
        initComponents();
        this.recorder = new SMSoundRecorder(f);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        record = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        grupoBotones.add(record);
        record.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/RecordDisabled_48x48.png"))); // NOI18N
        record.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/RecordPressed_48x48.png"))); // NOI18N
        record.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordMouseClicked(evt);
            }
        });
        getContentPane().add(record, new java.awt.GridBagConstraints());

        grupoBotones.add(stop);
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/StopDisabled_48x48.png"))); // NOI18N
        stop.setSelected(true);
        stop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/StopNormalRed_48x48.png"))); // NOI18N
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        getContentPane().add(stop, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if(recorder!=null){
            recorder.stop();
        }
      
    }//GEN-LAST:event_formInternalFrameClosed

    private void recordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordMouseClicked
        if(recorder!=null) recorder.record();
    }//GEN-LAST:event_recordMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
      if(recorder!=null) recorder.stop();
    }//GEN-LAST:event_stopMouseClicked

    //Cuando se activa la ventana cargamos la info
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JToggleButton record;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables
}
