/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import practicaFinal.Principal;
import sm.sound.SMClipPlayer;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author Ainokila
 */
public class VentanaInternaVideo extends javax.swing.JInternalFrame {
    
    private Principal parent;
    
    private EmbeddedMediaPlayer vlcplayer = null;
    private File fMedia;
    /**
     * Creates new form VentanaInterna
     */
    public VentanaInternaVideo(Principal padre,File f) {
        super(f.getName(),
          true, //resizable
          true, //closable
          true, //maximizable
          true);//iconifiable
                
        //this.setSize(0, 0);
        this.parent=padre;
        initComponents();
        
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER);
        vlcplayer = aVisual.getMediaPlayer();
    }
    
    public static VentanaInternaVideo getInstance(Principal p,File f){
        VentanaInternaVideo v = new VentanaInternaVideo(p,f);
        return (v.vlcplayer!=null?v:null);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        play = new javax.swing.JToggleButton();
        stop = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        grupoBotones.add(play);
        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/PlayDisabled_48x48.png"))); // NOI18N
        play.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/PlayPressed_48x48.png"))); // NOI18N
        play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playMouseClicked(evt);
            }
        });
        jPanel1.add(play);

        grupoBotones.add(stop);
        stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/StopDisabled_48x48.png"))); // NOI18N
        stop.setSelected(true);
        stop.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/practicaFinal/iconos/StopNormalRed_48x48.png"))); // NOI18N
        stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopMouseClicked(evt);
            }
        });
        jPanel1.add(stop);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.stop();
            }
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void playMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playMouseClicked
        if (vlcplayer != null) {
            if(vlcplayer.isPlayable()){
                //Si se estaba reproduciendo
                vlcplayer.play();
            } else {
                vlcplayer.playMedia(fMedia.getAbsolutePath());
            }
        } 
    }//GEN-LAST:event_playMouseClicked

    private void stopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopMouseClicked
        if (vlcplayer != null) {
            if (vlcplayer.isPlaying()) {
                vlcplayer.stop();
            } else {
                vlcplayer.stop();
            }
 
        }
    }//GEN-LAST:event_stopMouseClicked

    //Cuando se activa la ventana cargamos la info
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton play;
    private javax.swing.JToggleButton stop;
    // End of variables declaration//GEN-END:variables
}
