/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author Ainokila
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        herramientas = new javax.swing.ButtonGroup();
        colores = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        barraEstado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        lapiz = new javax.swing.JToggleButton();
        linea = new javax.swing.JToggleButton();
        cuadrado = new javax.swing.JToggleButton();
        circulo = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        relleno = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        color_blanco = new javax.swing.JToggleButton();
        color_amarillo = new javax.swing.JToggleButton();
        color_verde = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        color_negro = new javax.swing.JToggleButton();
        color_rojo = new javax.swing.JToggleButton();
        color_azul = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lienzo = new practica4.Lienzo();
        menu = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        menu_archivo_nuevo = new javax.swing.JMenuItem();
        menu_archivo_abrir = new javax.swing.JMenuItem();
        menu_archivo_guardar = new javax.swing.JMenuItem();
        menu_edicion = new javax.swing.JMenu();
        menu_edicion_verBarra = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        barraEstado.setText("Estado");
        jPanel1.add(barraEstado, java.awt.BorderLayout.LINE_START);
        jPanel1.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(100, 30));

        herramientas.add(lapiz);
        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Lapiz.gif"))); // NOI18N
        lapiz.setFocusable(false);
        lapiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lapiz.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapizActionPerformed(evt);
            }
        });
        jToolBar1.add(lapiz);

        herramientas.add(linea);
        linea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Linea.gif"))); // NOI18N
        linea.setFocusable(false);
        linea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        linea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jToolBar1.add(linea);

        herramientas.add(cuadrado);
        cuadrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Rectangulo.gif"))); // NOI18N
        cuadrado.setFocusable(false);
        cuadrado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuadrado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoActionPerformed(evt);
            }
        });
        jToolBar1.add(cuadrado);

        herramientas.add(circulo);
        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Ovalo.gif"))); // NOI18N
        circulo.setFocusable(false);
        circulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        circulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloActionPerformed(evt);
            }
        });
        jToolBar1.add(circulo);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel4.setLayout(new java.awt.BorderLayout());

        relleno.setText("Relleno");
        relleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoActionPerformed(evt);
            }
        });
        jPanel4.add(relleno, java.awt.BorderLayout.LINE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        color_blanco.setBackground(new java.awt.Color(255, 255, 255));
        colores.add(color_blanco);
        color_blanco.setBorder(null);
        color_blanco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_blanco.setPreferredSize(new java.awt.Dimension(30, 30));
        color_blanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_blancoActionPerformed(evt);
            }
        });
        jPanel5.add(color_blanco);

        color_amarillo.setBackground(new java.awt.Color(255, 255, 51));
        colores.add(color_amarillo);
        color_amarillo.setBorder(null);
        color_amarillo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_amarillo.setPreferredSize(new java.awt.Dimension(30, 30));
        color_amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_amarilloActionPerformed(evt);
            }
        });
        jPanel5.add(color_amarillo);

        color_verde.setBackground(new java.awt.Color(51, 204, 0));
        colores.add(color_verde);
        color_verde.setBorder(null);
        color_verde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_verde.setPreferredSize(new java.awt.Dimension(30, 30));
        color_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_verdeActionPerformed(evt);
            }
        });
        jPanel5.add(color_verde);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        color_negro.setBackground(new java.awt.Color(0, 0, 0));
        colores.add(color_negro);
        color_negro.setBorder(null);
        color_negro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_negro.setPreferredSize(new java.awt.Dimension(30, 30));
        color_negro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_negroActionPerformed(evt);
            }
        });
        jPanel7.add(color_negro);

        color_rojo.setBackground(new java.awt.Color(255, 51, 51));
        colores.add(color_rojo);
        color_rojo.setBorder(null);
        color_rojo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_rojo.setPreferredSize(new java.awt.Dimension(30, 30));
        color_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_rojoActionPerformed(evt);
            }
        });
        jPanel7.add(color_rojo);

        color_azul.setBackground(new java.awt.Color(0, 0, 255));
        colores.add(color_azul);
        color_azul.setBorder(null);
        color_azul.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        color_azul.setPreferredSize(new java.awt.Dimension(30, 30));
        color_azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_azulActionPerformed(evt);
            }
        });
        jPanel7.add(color_azul);

        jPanel3.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel3, java.awt.BorderLayout.LINE_START);
        jPanel4.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);
        jPanel2.add(jSeparator3, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jPanel2.add(lienzo, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        menu_archivo.setText("Archivo");

        menu_archivo_nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        menu_archivo_nuevo.setText("Nuevo");
        menu_archivo_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_archivo_nuevoActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_archivo_nuevo);

        menu_archivo_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        menu_archivo_abrir.setText("Abrir");
        menu_archivo_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_archivo_abrirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_archivo_abrir);

        menu_archivo_guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        menu_archivo_guardar.setText("Guardar");
        menu_archivo_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_archivo_guardarActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_archivo_guardar);

        menu.add(menu_archivo);

        menu_edicion.setText("Edicion");

        menu_edicion_verBarra.setSelected(true);
        menu_edicion_verBarra.setText("Ver barra estado");
        menu_edicion_verBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_edicion_verBarraActionPerformed(evt);
            }
        });
        menu_edicion.add(menu_edicion_verBarra);

        menu.add(menu_edicion);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_archivo_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_archivo_nuevoActionPerformed
        lienzo.clear();
    }//GEN-LAST:event_menu_archivo_nuevoActionPerformed

    private void menu_archivo_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_archivo_abrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            BufferedImage buffer;
            try{
                buffer = ImageIO.read(f);
                this.lienzo.getGraphics().drawImage(buffer, 0, 0, null);
            }catch (Exception e) {      
                
            }      
        }
    }//GEN-LAST:event_menu_archivo_abrirActionPerformed

    private void lapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapizActionPerformed
        lienzo.setHerramienta(Herramienta.LAPIZ);
        barraEstado.setText("Punto");
    }//GEN-LAST:event_lapizActionPerformed

    private void rellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoActionPerformed
        lienzo.cambiaRelleno(relleno.isSelected());
    }//GEN-LAST:event_rellenoActionPerformed

    private void color_amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_amarilloActionPerformed
        lienzo.setColor(Color.AMARILLO);
    }//GEN-LAST:event_color_amarilloActionPerformed

    private void circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloActionPerformed
        lienzo.setHerramienta(Herramienta.CIRCULO);
        barraEstado.setText("Ovalo");

    }//GEN-LAST:event_circuloActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        lienzo.setHerramienta(Herramienta.LINEA);
        barraEstado.setText("Linea");
    }//GEN-LAST:event_lineaActionPerformed

    private void cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoActionPerformed
        lienzo.setHerramienta(Herramienta.RECTANGULO);
        barraEstado.setText("Rectangulo");
    }//GEN-LAST:event_cuadradoActionPerformed

    private void color_negroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_negroActionPerformed
        lienzo.setColor(Color.NEGRO);
    }//GEN-LAST:event_color_negroActionPerformed

    private void color_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_rojoActionPerformed
        lienzo.setColor(Color.ROJO);
    }//GEN-LAST:event_color_rojoActionPerformed

    private void color_azulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_azulActionPerformed
        lienzo.setColor(Color.AZUL);
    }//GEN-LAST:event_color_azulActionPerformed

    private void color_blancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_blancoActionPerformed
        lienzo.setColor(Color.BLANCO);
    }//GEN-LAST:event_color_blancoActionPerformed

    private void color_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_verdeActionPerformed
        lienzo.setColor(Color.VERDE);
    }//GEN-LAST:event_color_verdeActionPerformed

    private void menu_archivo_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_archivo_guardarActionPerformed
        JFileChooser dlg = new JFileChooser();


        int resp = dlg.showOpenDialog(this);
        if( resp == JFileChooser.APPROVE_OPTION) {
            
            File f = dlg.getSelectedFile();
            BufferedImage buffer = new BufferedImage(lienzo.getSize().width, lienzo.getSize().height, BufferedImage.TYPE_INT_ARGB); 
            Graphics grafico = buffer.createGraphics();
            this.lienzo.paint(grafico);  //this == JComponent
            grafico.dispose();
            try{
                ImageIO.write(buffer,"png",new File(f.getAbsoluteFile().toString()+".png"));
            }catch (Exception e) {
            
            }

        }
    }//GEN-LAST:event_menu_archivo_guardarActionPerformed

    private void menu_edicion_verBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_edicion_verBarraActionPerformed
        this.barraEstado.setVisible(this.menu_edicion_verBarra.isSelected());
    }//GEN-LAST:event_menu_edicion_verBarraActionPerformed

    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barraEstado;
    private javax.swing.JToggleButton circulo;
    private javax.swing.JToggleButton color_amarillo;
    private javax.swing.JToggleButton color_azul;
    private javax.swing.JToggleButton color_blanco;
    private javax.swing.JToggleButton color_negro;
    private javax.swing.JToggleButton color_rojo;
    private javax.swing.JToggleButton color_verde;
    private javax.swing.ButtonGroup colores;
    private javax.swing.JToggleButton cuadrado;
    private javax.swing.ButtonGroup herramientas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton lapiz;
    private practica4.Lienzo lienzo;
    private javax.swing.JToggleButton linea;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenuItem menu_archivo_abrir;
    private javax.swing.JMenuItem menu_archivo_guardar;
    private javax.swing.JMenuItem menu_archivo_nuevo;
    private javax.swing.JMenu menu_edicion;
    private javax.swing.JCheckBoxMenuItem menu_edicion_verBarra;
    private javax.swing.JCheckBox relleno;
    // End of variables declaration//GEN-END:variables
}
